[MultiThreshold] Generalize data layouts for node execution
fastmachinelearning/qonnx pull request #143
Opened 2024-09-13 13:44 UTC by iksnagreb

The relevant aspect of the data layout annotation seems to be which axis is labeled as the channel dimension "C": We do not actually have to care about the total number and ordering of the other axes, as long as we can find the index of the "C" axis and swap to have "C" at index 1 for node execution (and swap it back afterwards).

Falls back to the default assumption that "C" is at index 1 if there is no layout annotation, which is equivalent to the "NCHW" or "NC" layouts.

This is a rather experimental change which might break existing code and is currently still restricted to the well-known 2-, 3- and 4-dimensional layouts.

This PR is based on #92 which is less experimental and should be merged first (#92 also does not risk breaking existing code as it only adds new special cases).

2024-12-17 13:06 UTC, maltanar commented
Instead of relying on data layout strings, how about we switch to an attribute `axis` (like many standard ONNX ops do) to indicate the location (index) of the channels axis? I'd actually prefer to deprecate the old `data_layout` attribute, and I think we can still keep backwards compatibility by treating `data_layout=NCHW` as `axis=1` and `data_layout=NHWC` as `axis=-1`. If the interpretation of the two attributes disagree, the `axis` one can dominate.

2026-01-23 15:05 UTC, makoeppel requested changes
I think here we only have to rebase. This was already approved and merged by @maltanar. Or were there some new changes? If so I would maybe prefer to create a new branch.

2026-01-23 15:55 UTC, iksnagreb commented
> I think here we only have to rebase. This was already approved and merged by @maltanar. Or were there some new changes? If so I would maybe prefer to create a new branch.

Hm, @maltanar contributed some significant improvements to the `multithreshold` implementation with #201, but I'd argue we want to keep the more general channel axis resolution from this PR. I will rebase and resolve the conflict.

2026-02-11 22:34 UTC, jmitrevs commented on src/qonnx/custom_op/general/multithreshold.py
> +        v = v.swapaxes(cdim, 1)
Does this always work? Is it an improvement over using the channels_last parameter?

2026-02-13 17:48 UTC, iksnagreb commented on src/qonnx/custom_op/general/multithreshold.py
> +        v = v.swapaxes(cdim, 1)
For 1d, 2d, 3d and 4d input this is fine and matches the previous behavior. Looking at it now, I just realized that in case there is no fallback (>= 5d) or for 0d, it will try indexing into a `None`. Though, as far as I am aware, this would not affect any model we are supporting at the moment. Still this should be address. I will add a quick workaround, though the entire layout mechanism is long overdue for a proper rework...

2026-02-13 17:52 UTC, jmitrevs commented on src/qonnx/custom_op/general/multithreshold.py
> +        v = v.swapaxes(cdim, 1)
Is it possible to just use the channels_last flag?

2026-02-13 17:59 UTC, iksnagreb commented on src/qonnx/custom_op/general/multithreshold.py
> +        v = v.swapaxes(cdim, 1)
Not really, channels_last can only differentiate between channels at axis 1 or -1, but we had instances where channels could end up at any index, at least temporarily while transforming the model. Usually we always end up with channels last (anything else cannot really be implemented in FINN at the moment), but to get there we might transition through a few mixed-up layouts, but we still want to be able to execute/simulate this.

2026-02-17 21:53 UTC, jmitrevs approved these changes

2026-02-17 21:54 UTC, merged