A first sample version of `FloatQuant`
fastmachinelearning/qonnx pull request #159
Opened 2024-12-09 20:51 UTC by nghielme

Please, consider that the function should be tested more extensively.
Sample `FloatQuant` function implemented. A sample use of the function can be found in the `Examples`. `±inf` are clipped to `±max_val`. `±NaN` are mapped to `±NaN`. The zero is always representable. I tested with subnormals (to be intended as subnormals for the output representation) and the quantizer represented the subnormals with no loss (I didn't extensively tested this part though). I tested the function against Brevitas `FloatQuant` implementation: they do not always match. For example I think `0.3125` should be representable (`x == xq`) by a float quantizer with 4bits for mantissa, 4bits for the exponent, 0 bias and 1bit for the sign. Brevitas `FloatQuant` implementation quantize it to `0.25`. Not sure what I should consider correct for this case.

2024-12-10 10:13 UTC, nickfraser commented
Brevitas developer here, thanks for this concrete example - I will look into it ASAP!

2024-12-10 10:20 UTC, nickfraser commented
Yes, please do - if you can provide minimal examples as well, this will make it much easier for us as well 🙏. Note, `dev` is our staging branch, so please make sure any issues still exist in `dev`.

If you have proposed solutions, feel free to make PRs as well (pointing to `dev`), so long as you follow our [contributor guidelines](https://github.com/Xilinx/brevitas/blob/dev/CONTRIBUTING.md).

2024-12-12 09:58 UTC, nghielme commented on src/qonnx/custom_op/general/floatquant.py
> +    lt_subnorm_to_zero=False,
@maltanar , this name is terrible! Please, help me in finding a better one 🤦‍♂️

2025-03-07 09:12 UTC, maltanar requested changes
Thanks @nghielme ! Looking good, but needs a few fixes before merging.

2025-03-07 09:12 UTC, maltanar commented on docs/qonnx-custom-ops/floatquant_op.md
> +```python
let's add a comment that links this back to the source file, in case it changes in the future but we forget to update it here.
e.g.
`# see src/qonnx/custom_op/general/floatquant.py for up-to-date implementation`

2025-03-07 09:12 UTC, maltanar commented on tests/custom_op/test_floatquant.py
> +from qonnx.custom_op.general.floatquant import compute_max_val, float_quantize
wrong name imported? the impl seems to have been renamed to `float_quant` (and no longer `float_quantize`)

2025-03-07 09:12 UTC, maltanar commented on src/qonnx/custom_op/general/floatquant.py
> +    signed,
since we have a notion of a default exponent bias (as implemented by the `compute_default_exponent_bias` function) I suggest to enable using the default by setting `exponent_bias=None`.  in that case `signed` should be either moved up in the parameter list to come before the params with default values, or assigned some default value (True?) itself

2025-03-07 09:12 UTC, maltanar commented on tests/custom_op/test_floatquant.py
> +    assert np.all(float_quantize(testcase_f, unit_scale, 2, 3, lt_subnorm_to_zero=True) == 0.0)
missing `signed` and perhaps `exponent_bias` args?

2025-03-07 09:12 UTC, maltanar commented on tests/custom_op/test_floatquant.py
> +
please also add the test with the example executing QONNX exported from Brevitas & comparing against (pre-generated) reference value from Brevitas, which you shared with me previously

2025-04-10 08:33 UTC, maltanar approved these changes

2025-04-10 08:33 UTC, merged